from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


SceneType = Literal["grid", "height_map"]
CameraMode = Literal["top_down", "isometric", "follow"]
RunMode = Literal["canonical", "user"]

PrimitiveType = Literal[
    "empty_tile",
    "floor_tile",
    "orange",
    "land",
    "water",
    "wall",
    "character",
    "destination",
    "height_block",
]

IdleAnimation = Literal[
    "none",
    "gentle_bounce",
    "gentle_float",
    "sick_wobble",
    "water_ripple",
    "soft_glow",
]

AnimationEffect = Literal[
    "none",
    "cell_pulse",
    "queue_glow",
    "infection_wave",
    "transform_entity",
    "island_discovery",
    "frontier_expand",
    "path_reveal",
    "water_flow",
    "dual_ocean_glow",
    "result_reveal",
]

IntroActionType = Literal[
    "show_grid",
    "camera_pan",
    "show_title",
    "highlight_sources",
    "highlight_destination",
]

SUPPORTED_EFFECTS: frozenset[str] = frozenset(
    AnimationEffect.__args__  # type: ignore[attr-defined]
)
SUPPORTED_PRIMITIVES: frozenset[str] = frozenset(
    PrimitiveType.__args__  # type: ignore[attr-defined]
)


class StrictModel(BaseModel):
    """OpenAI structured outputs require additionalProperties=false."""

    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------------------------
# Request / problem packages
# ---------------------------------------------------------------------------


class GenerateAnimationRequest(BaseModel):
    exampleIndex: int = 0
    userCode: str | None = None
    style: str = "derpy"


class ProblemPackage(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    id: str
    directory: Path
    problem_markdown: str
    config: dict[str, Any]
    solution: str


class ProblemSummary(BaseModel):
    id: str
    title: str
    difficulty: str
    category: str
    algorithm: list[str] = Field(default_factory=list)


class ProblemDetail(BaseModel):
    id: str
    title: str
    difficulty: str
    category: str
    algorithm: list[str]
    problemMarkdown: str
    config: dict[str, Any]


# ---------------------------------------------------------------------------
# Execution (truthful algorithm output — never invented by the LLM)
# ---------------------------------------------------------------------------


class ExecutionResult(BaseModel):
    result: Any
    expected: Any
    passed: bool
    initialState: dict[str, Any]
    finalState: dict[str, Any]
    events: list[dict[str, Any]]


# ---------------------------------------------------------------------------
# Visual plan (presentation only — generated by the LLM)
# ---------------------------------------------------------------------------


class CameraConfig(StrictModel):
    mode: CameraMode
    position: list[float] = Field(min_length=3, max_length=3)
    target: list[float] = Field(min_length=3, max_length=3)


class SceneSpec(StrictModel):
    type: SceneType
    theme: str = Field(min_length=1, max_length=80)
    backgroundColor: str
    camera: CameraConfig


class EntityDefinition(StrictModel):
    primitive: PrimitiveType
    variant: str = Field(min_length=1, max_length=60)
    color: str
    label: str
    idleAnimation: IdleAnimation


class EventAnimation(StrictModel):
    effect: AnimationEffect
    durationMs: int = Field(ge=100, le=3000)
    color: str | None
    explanation: str = Field(min_length=1, max_length=240)


class IntroAction(StrictModel):
    action: IntroActionType
    durationMs: int = Field(ge=100, le=3000)
    text: str | None


class EntityBinding(StrictModel):
    """LLM-friendly list item; converted to a dict for the frontend."""

    cellValue: str = Field(min_length=1, max_length=40)
    entity: EntityDefinition


class EventBinding(StrictModel):
    """LLM-friendly list item; converted to a dict for the frontend."""

    eventType: str = Field(min_length=1, max_length=60)
    animation: EventAnimation


class ParsedVisualPlan(StrictModel):
    """Structured-output shape for OpenAI (lists, not open-ended dicts)."""

    scene: SceneSpec
    entities: list[EntityBinding] = Field(min_length=1, max_length=20)
    eventBindings: list[EventBinding] = Field(min_length=1, max_length=40)
    intro: list[IntroAction] = Field(min_length=1, max_length=8)


class GeneratedVisualPlan(BaseModel):
    scene: SceneSpec
    entities: dict[str, EntityDefinition]
    eventBindings: dict[str, EventAnimation]
    intro: list[IntroAction]


class AnimationPackage(BaseModel):
    problemId: str
    runMode: RunMode
    execution: ExecutionResult
    visualPlan: GeneratedVisualPlan
